<?php

/**
 * Implementation of hook_permission().
 */
function rj_simulador_permission()
{
  return array(
    'crear partidas' => array(
      'title' => t('Crear nuevas partidas'),
      'description' => t('Permite a los usuarios con este permiso almacenar los datos de una partida'),
    ),
    'gestionar estadisticas' => array(
      'title' => t('Ver la pagina de estadisticas'),
      'description' => t('Permite a los usuarios con este permiso ver sus estadísticas de partida'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function rj_simulador_menu()
{
  $items = array();
  $items['mis_partidas'] = array(
    'title' => 'Mis partidas realizadas',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rj_simulador_pagina_form'),
    'file' => 'rj_simulador.pages.inc',
    'access arguments' => array('user access'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['mis_partidas/%'] = array(
    'title' => 'Información de mi partida',
    'file' => 'rj_simulador.pages.inc',
    'page callback' => 'partida_page',
    'page arguments' => array(1),
    'access arguments' => array('user access'),
    'type' => MENU_CALLBACK,
  );
  $items['prueba/form'] = array(
    'title' => 'Formulario',
    'file' => 'rj_simulador.forms.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rj_simulador_pagina_form'),
    'access arguments' => array('user access'),
    'type' => MENU_CALLBACK,
  );
  /*$items['admin/content/estadisticas'] = array(
    'title' => 'Gestionar estadisticas',
    'page callback' => 'listado_estadisticas_page',
    'file' => 'rj_simulador.pages.inc',
    'access arguments' => array('gestionar estadisticas'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/estadisticas/crear-estadistica'] = array(
    'title' => 'Crear una nueva estadistica',
    'description' => 'Crear una nueva estadistica',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rj_simulador_pagina_form'),
    'file' => 'rj_simulador.forms.inc',
    'access arguments' => array('gestionar estadisticas'),
    'type' => MENU_LOCAL_ACTION,
  );*/
  return $items;
}

/**
 *  Implements hook_services_resources().
 */
function rj_simulador_services_resources()
{
  // Include resources definitions
  module_load_include('inc', 'rj_simulador', 'resources/rj_simulador_partida.resource');
  $resources = array();
  $resources += partida_resource_definition();
  return $resources;
}


function rj_simulador_theme()
{
  return array(
    'lista_partidas' => array(
      'template' => 'templates/lista-partidas',
      'variables' => array('upper_left' => NULL, 'upper_right' => NULL, 'main_content' => NULL)
    )
  );
}


/**
 *  Implements hook_preprocess_HOOK().
 */
function rj_simulador_preprocess_lista_partidas(&$variables)
{
}