<?php
/**
 * Implementation of hook_permission().
 */
function rj_simulador_permission() {
  return array(
    'gestionar estadisticas' => array(
      'title' => t('Ver la pagina de estadisticas'),
      'description' => t('Permite a los usuarios con este permiso ver sus estadísticas de partida'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function rj_simulador_menu() {
  $items = array();
  $items['admin/content/estadisticas'] = array(
    'title' => 'Gestionar estadisticas',
    'page callback' => 'listado_estadisticas_page',
    'file' => 'rj_simulador.forms.inc',
    'access arguments' => array('listar helice encuesta'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/estadisticas/crear-estadistica'] = array(
    'title' => 'Crear una nueva estadistica',
    'description' => 'Crear una nueva estadistica',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rj_simulador_pagina_form'),
    'file' => 'rj_simulador.forms.inc',
    'access arguments' => array('gestionar estadisticas'),
    'type' => MENU_LOCAL_ACTION,
  );
  return $items;
}
